# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Sample Statistic" 
email: no-reply@samplestatistic.com
description: >- # this means to ignore newlines until "baseurl:"
  Collection of statistical concepts explained in a very simple way.
  Learn the statistics used in engineering and data science from real-life and code examples.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samplestatistic.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
# logo: "/assets/images/just-the-docs.png"

permalink: pretty
aux_links:
  "Edit on GitHub":
    - "https://github.com/iomath/sample-statistic-website"

footer_content: "Copyright &copy; 2020."

ga_tracking: UA-171199155-1
ga_tracking_anonymize_ip: true

# Build settings
#remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap  

exclude:
  - Makefile

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: samplestatistic

defaults:
  -
    scope:
      path: "**/index.md"
      type: "pages"
    values:
      layout: "default"
      has_children: true
      comments: false
      nav_exclude: false
