# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Sample Statistic" 
email: no-reply@samplestatistic.com
description: >- # this means to ignore newlines until "baseurl:"
  Collection of statistical concepts explained in a very simple way.
  Learn the statistics used in engineering and data science from real-life and code examples.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samplestatistic.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
# logo: "/assets/images/just-the-docs.png"

permalink: pretty
aux_links:
  "Edit on GitHub":
    - "https://github.com/iomath/sample-statistic-website"

footer_content: "Copyright &copy; 2020."

ga_tracking: UA-171199155-1
ga_tracking_anonymize_ip: true

# Build settings
#remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Makefile

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: samplestatistic
